# environment
alpha: 2.0
beta: 1.0
holding_cost: 0.1
backlog_cost: 0.5
setup_cost: 0.1
unit_cost: 0.3
max_inventory: 50

# training
warmup_period: 60
train_period: 500
s_init: 2.0
S_init: 4.0
rho_init: 0.0
sigma: 0.1
tau: 0.1
sigma_decay: 0.99
tau_decay: 0.99
b1: 0.01
b2: 0.01
gamma1_base: 0.1
gamma2_base: 0.05
gamma_decay: 0.01

# regime switching
regime_switching: true
regime_sequence:
  - [4.0, 2.0]    # Case 1    (2,1)
  - [0.8, 0.4]    # Case 2    (2,5)
  - [0.4, 0.2]    # Case 3    (2,10)
  - [25.0, 5.0]   # Case 4    (5,1)
  - [5.0, 1.0]    # Case 5    (5,5)
  - [2.5, 0.5]    # Case 6    (5,10)
  - [100.0, 10.0] # Case 7    (10,1)
  - [20.0, 2.0]   # Case 8    (10,5)
  - [10.0, 1.0]   # Case 9    (10,10)
